# Generated by Django 4.0.1 on 2022-02-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('mulai', models.DateField()),
                ('akhir', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AbsencePeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_list', models.CharField(default='0000000000000000000000000000000', max_length=50)),
                ('exit_list', models.CharField(default='0000000000000000000000000000000', max_length=50)),
                ('isStarted', models.BooleanField(default=False)),
                ('nth_absence', models.IntegerField(default=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
