# Generated by Django 3.2.6 on 2022-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('mulai', models.DateField()),
                ('akhir', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
