# Generated by Django 4.0.1 on 2022-02-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_absencepeserta'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencepeserta',
            name='start_at',
            field=models.CharField(default='', max_length=100),
        ),
    ]
