# Generated by Django 4.0.1 on 2022-02-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_absencepeserta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencepeserta',
            name='peserta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.peserta'),
        ),
    ]
