# Generated by Django 4.0.1 on 2022-02-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_absencepeserta_peserta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencepeserta',
            name='peserta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='api.peserta'),
        ),
        migrations.AlterField(
            model_name='absencepeserta',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
