# Generated by Django 4.0.1 on 2022-02-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_absencepeserta_peserta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absencepeserta',
            name='entrance_list',
            field=models.CharField(default='0000000000000000000000000000000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='absencepeserta',
            name='exit_list',
            field=models.CharField(default='0000000000000000000000000000000000', max_length=50),
        ),
    ]
