# Generated by Django 4.0.1 on 2022-02-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_absencepeserta_entrance_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencepeserta',
            name='finish_at',
            field=models.CharField(default='', max_length=100),
        ),
    ]
