# Generated by Django 4.0.1 on 2022-01-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Co-Admin'), (3, 'Peserta')], default=2, null=True),
        ),
    ]
